version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  generator:
    build:
      context: ./puppeteer
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    expose:
      - 3000

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
  redis:
    image: redis:latest
    expose:
      - 6379

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info 
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - web

volumes:
  postgres_data: